apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "--sync-wait 60"
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/ds-argo.git
    targetRevision: HEAD
    path: argocd/pipelines
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true