apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        - name: auth-volume
          mountPath: /auth
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry"
      initContainers:
      - name: create-htpasswd
        image: httpd:2.4
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /auth
            touch /auth/htpasswd
            for key in $(env | cut -d= -f1); do
              val=$(eval "echo \$$key")
              if [ ! -z "$key" ] && [ ! -z "$val" ]; then
                htpasswd -Bb /auth/htpasswd "$key" "$val"
              fi
            done
        envFrom:
        - configMapRef:
            name: registry-users
        volumeMounts:
        - name: auth-volume
          mountPath: /auth
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-devsoul-pvc
      - name: auth-volume
        emptyDir: {}