apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"     # Sync wave annotation to ensure the minimum time between syncs
    argocd.argoproj.io/sync-options: "--sync-wait 30"  # Sync options annotation to set the sync wait time to 60 seconds
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/ds-argo.git
    targetRevision: HEAD
    path: argocd/apps/pgadmin
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true