apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsoul-portfolio
  namespace: devsoul-portfolio
  labels:
    app: devsoul-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsoul-portfolio
  template:
    metadata:
      labels:
        app: devsoul-portfolio
    spec:
      imagePullSecrets:
        - name: devsoul-registry-secret
      containers:
      - name: devsoul-portfolio
        image: repo.devsoul.net/devsoul-portfolio-next:fbcd6d168bcb5e6d2a4b24aa1636fa27e8130a63
        ports:
        - containerPort: 3000