apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsoul-portfolio
  namespace: devsoul-portfolio
  labels:
    app: devsoul-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsoul-portfolio
  template:
    metadata:
      labels:
        app: devsoul-portfolio
    spec:
      imagePullSecrets:
        - name: devsoul-registry-secret
      containers:
      - name: devsoul-portfolio
        image: repo.devsoul.net/devsoul-portfolio-next:8a35b84e45cc5c91ffdcab0e202b1c0d2a65e037
        ports:
        - containerPort: 3000