apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsoul-portfolio
  namespace: devsoul-portfolio
  labels:
    app: devsoul-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsoul-portfolio
  template:
    metadata:
      labels:
        app: devsoul-portfolio
    spec:
      imagePullSecrets:
        - name: devsoul-registry-secret
      containers:
      - name: devsoul-portfolio
        image: repo.devsoul.net/devsoul-portfolio-next:1ed88925c2746f0641a2e5264356786568d56dca
        ports:
        - containerPort: 3000