
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: default
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: default
  set:
    nfs.server: 192.168.1.201
    nfs.path: /usb/data
    storageClass.name: nfs
    storageClass.reclaimPolicy: Retain
    storageClass.volumeBindingMode: WaitForFirstConsumer


#File Path: /var/lib/rancher/k3s/server/manifests/nfs.yaml
# apt install nfs-common