apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsales-backend
  namespace: devsales-backend
  labels:
    app: devsales-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsales-backend
  template:
    metadata:
      labels:
        app: devsales-backend
    spec:
      imagePullSecrets:
        - name: devsoul-registry-secret
      containers:
      - name: devsales-backend
        image: repo.devsoul.net/devsales-backend-next:88470df9320f4e373728885ae4307db2576359f2
        ports:
        - containerPort: 3000
        envFrom:
            - secretRef:
                name: devsales-backend-dev-secret