apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: devsales-backend-dev-secret-store
  namespace: devsales-backend
spec:
  provider:
    # provider type: gitlab
    gitlab:
      url: https://gitlab.devsoul.net/
      auth:
        SecretRef:
          accessToken:
            name: gitlab-access-secret
            key: token
      projectID: "59"
      # groupIDs: "**groupID(s) go here**"
      # inheritFromGroups: "**automatically looks for variables in parent groups**"
      environment: "dev"

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: devsales-backend-dev-secret
  namespace: devsales-backend
spec:
  refreshInterval: 5m

  secretStoreRef:
    kind: SecretStore
    name: devsales-backend-dev-secret-store # Must match SecretStore on the cluster

  target:
    name: devsales-backend-dev-secret # Name for the secret to be created on the cluster
    creationPolicy: Owner

  # each secret name in the KV will be used as the secret key in the SECRET k8s target object
  dataFrom:
    - extract:
        key: "ENV"

