apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-db
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: "Always"
      initContainers:
      - name: init-chmod-data
        image: busybox
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
        command:
        - sh
        - -c
        - |
          echo "Initializing permissions..."
          mkdir -p /var/lib/postgresql/data
          chmod -R 0700 /var/lib/postgresql/data
          chown -R 999:999 /var/lib/postgresql/data
          echo "Permissions set:"
          ls -la /var/lib/postgresql/data
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:latest
        securityContext:
          runAsUser: 999
          runAsGroup: 999
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-devsoul-pvc
