apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
