---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-zee-im
spec:
  secretName: wildcard-zee-im
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - "*.k.zee.im"
  - "k.zee.im"
